### ISSUE TITLE
opencsd and linux kernel version

### ISSUE THREAD

**Issue by wwladikw** [Linaro/OpenCSD#35]
Hello,

I have an arm64 based board and was successfully ran coresight tracing on on some Linux backport from Linaro for 4.9. Right now it seems things get migrated to upstream Linux and I am no longer able to collect perf data.

My setup looks like 5.4.78 Linux in combination with Opencsd v0.14.4.

```
$ perf record -e cs_etm/@tmc_etr0/ --per-thread uname
Couldn't synthesize bpf events.
Linux
[ perf record: Woken up 1 times to write data ]
[ perf record: Captured and wrote 0.096 MB perf.data ]

$ perf report --stdio
Error:
The perf.data data has no samples!

```

Question would be if there is some specific version of Linux/perf required to run this out of the box?
There is also this error message "Couldn't synthesize bpf events." which confuses me as well..

Thank you!

**Comment by mikel-armbb** [comment]
Hi,

The latest version of OpenCSD has been tested against perf and shown to work. The issues you are seeing are therefore unlikely to be related to OpenCSD. There is no limitation for kernel versions / OpenCSD. other than the fact that later kernel versions will require later OpencSD due to compile time changes that add new packet types. If your perf compiles with OpenCSD then it is compatible. 

Please ensure that your perf and your kernel are built from the same tree. Try the perf report -D option to check for trace packets in your file.

Thanks 

Mike

**Comment by wwladikw** [comment]
Thanks for the comments Mike.

> Please ensure that your perf and your kernel are built from the same tree.

Yes, this is ensured.

> Try the perf report -D option to check for trace packets in your file.

There I can see :

`0x178 [0x928]: event: 70
.
. ... raw event: size 2344 bytes
.  0000:  46 00 00 00 00 00 28 09 03 00 00 00 00 00 00 00  F.....(.........
`
and more events.

I will try a more recent Linux version.

Thanks,
- Wladi

**Comment by mikel-armbb** [comment]
Hi,

OK - the more up to date version you try, the  more likely we are able to provide support. 

I am going to close this issue now, as it does not seem to be directly related to OpenCSD.

However, for general perf / CoreSight issues I recommend posting on the CoreSight mailing list - detailed in the OpenCSD README.md => coresight@lists.linaro.org .

This list is used by more people than the OpenCSD github, and gets the latest update patches to CoreSight and many of the etm trace related perf posted there. 

Regards

Mike
